import { useEffect, useRef, useState } from 'react';
import type { PointerEvent } from 'react';
import { Box, ChevronDown, Heart, Menu, Search, ShoppingBag, X, Truck, RotateCcw, Headphones, Plus, Minus, AudioLines, Bluetooth, BatteryFull, ShieldCheck, Volume2, Play, Pause, MoveUpRight } from 'lucide-react';
import { products } from './products';
import { money } from './types';
import { ProductCard, StoreProvider, useStore } from './Commerce';
const scrollTo=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
export default function App(){return <StoreProvider brand="VOLT" products={products}><Volt/></StoreProvider>;}
function Volt(){
 const store=useStore();const [category,setCategory]=useState('Todos');const [sort,setSort]=useState('featured');const [menu,setMenu]=useState(false);const [faq,setFaq]=useState<number|null>(0);const [playing,setPlaying]=useState(false);const hero=useRef<HTMLDivElement>(null);const audio=useRef<AudioContext|null>(null);const oscillators=useRef<OscillatorNode[]>([]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[category,sort]);
 useEffect(()=>()=>{oscillators.current.forEach(o=>{try{o.stop();}catch{}});void audio.current?.close();},[]);
 const stopAudio=()=>{oscillators.current.forEach(o=>{try{o.stop();}catch{}});oscillators.current=[];void audio.current?.suspend();setPlaying(false);};
 const toggleSound=()=>{if(playing){stopAudio();return;}try{const context=audio.current??new AudioContext();audio.current=context;void context.resume();const gain=context.createGain();gain.gain.setValueAtTime(0,context.currentTime);gain.gain.linearRampToValueAtTime(.018,context.currentTime+.8);gain.connect(context.destination);[130.81,164.81,196,261.63].forEach((hz,i)=>{const oscillator=context.createOscillator();oscillator.type='sine';oscillator.frequency.value=hz;oscillator.detune.value=i*2;oscillator.connect(gain);oscillator.start();oscillators.current.push(oscillator);});setPlaying(true);}catch{store.notify('O áudio não está disponível neste navegador');}};
 const tilt=(e:PointerEvent<HTMLDivElement>)=>{if(e.pointerType!=='mouse'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();hero.current?.style.setProperty('--rx',`${-((e.clientY-r.top)/r.height-.5)*9}deg`);hero.current?.style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*12}deg`);};
 const navigate=(id:string)=>{setMenu(false);scrollTo(id);};
 const filtered=products.filter(p=>category==='Todos'||p.category===category).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:products.indexOf(a)-products.indexOf(b));
 const info=(title:string,body:string)=>store.open({type:'info',title,body});
 const faqs=[['O que muda com o cancelamento de ruído?','O ANC do V01 Studio é apresentado como um recurso adaptativo que reduz distrações do ambiente. As especificações são conceituais e pertencem a um produto fictício deste portfólio.'],['Funciona com meu celular ou notebook?','Na proposta de produto, todos os dispositivos VOLT usam Bluetooth 5.3 e são compatíveis com fontes de áudio Bluetooth. O V01 apresenta conexão simultânea com dois dispositivos.'],['Como funciona a compra?','Você pode explorar os produtos, escolher acabamentos, adicionar à sacola e concluir um checkout demonstrativo. Nenhum pagamento é cobrado. Este site é um projeto exclusivamente frontend.']];
 return <><a className="skip-link" href="#colecao">Ir para a coleção</a><div className="announcement"><span>FRETE GRÁTIS ACIMA DE R$ 500</span><span>AMPLIFIQUE SEU DIA.</span><span>BR / PT</span></div><header className="site-header"><a className="wordmark" href="#inicio" aria-label="VOLT, início">VOLT<span>®</span></a><nav aria-label="Navegação principal"><a href="#colecao" onClick={e=>{e.preventDefault();navigate('colecao');}}>Produtos</a><a href="#tecnologia" onClick={e=>{e.preventDefault();navigate('tecnologia');}}>A experiência</a><a href="#manifesto" onClick={e=>{e.preventDefault();navigate('manifesto');}}>Por que VOLT</a></nav><div className="header-actions"><button className="icon-button" aria-label="Buscar produtos" onClick={()=>store.open({type:'search'})}><Search size={20}/></button><button className="icon-button favorites-button" aria-label="Ver favoritos" onClick={()=>store.open({type:'favorites'})}><Heart size={20}/>{store.favorites.length>0&&<span className="count">{store.favorites.length}</span>}</button><button className="bag-button" aria-label={`Abrir sacola, ${store.count} itens`} onClick={()=>store.open({type:'cart'})}><ShoppingBag size={19}/><span className="bag-count">{store.count}</span></button><button className="mobile-menu icon-button" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<nav className="mobile-navigation" aria-label="Navegação móvel"><button onClick={()=>navigate('colecao')}>Produtos</button><button onClick={()=>navigate('tecnologia')}>A experiência</button><button onClick={()=>navigate('manifesto')}>Por que VOLT</button><button onClick={()=>{setMenu(false);store.open({type:'favorites'});}}>Favoritos</button></nav>}
 <main id="inicio"><section className="hero section-shell"><div className="hero-copy"><div className="launch-label"><span>NEW DROP</span><span>V01 STUDIO / PLATINUM</span></div><h1>SOM.<br/> SEM.<br/> <em>LIMITES.</em></h1><p>Desligue o ruído. Entre na música.<br/> O seu mundo, na sua frequência.</p><div className="hero-buttons"><button className="button primary" onClick={()=>store.open({type:'product',product:products[0]})}>Conheça o V01<Plus size={18}/></button><button className="hero-3d" onClick={()=>{store.open({type:'product',product:products[0]});}}><Box size={18}/>Explore em 3D</button></div><div className="hero-proof"><span className="sound-mark"><AudioLines size={28}/></span><div>40 HORAS DE MÚSICA.<br/> <span>ZERO TEMPO PARA DISTRAÇÕES.</span></div></div></div><div className="hero-art" ref={hero} onPointerMove={tilt} onPointerLeave={()=>{hero.current?.style.setProperty('--rx','0deg');hero.current?.style.setProperty('--ry','0deg');}}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><span className="hero-model-number" aria-hidden="true">V01</span><span className="hero-vertical">ENGINEERED FOR YOUR FREQUENCY</span><button className="hero-product" aria-label="Explorar o V01 Studio" onClick={()=>store.open({type:'product',product:products[0]})}><img src={import.meta.env.BASE_URL+'images/headphones.webp'} alt="Headphone V01 Studio com acabamento de alumínio platinum e almofadas cinza" width="1000" height="1000" fetchPriority="high"/></button><button className="hero-product-tag" onClick={()=>store.open({type:'product',product:products[0]})}><span>V01 STUDIO<small>PLATINUM EDITION</small></span><span>{money(products[0].price)}<MoveUpRight size={18}/></span></button><span className="hero-coordinate">01° / 360° · PURE SOUND</span></div></section>
 <div className="spec-bar section-shell"><div><Headphones size={23}/><span>40 <small>h</small><p>Bateria que acompanha</p></span></div><div><AudioLines size={24}/><span>ANC<p>Silêncio, sob controle</p></span></div><div><Bluetooth size={23}/><span>5.3<p>Conexão sem limites</p></span></div><div><Volume2 size={23}/><span>Hi-Res<p>Ouça cada detalhe</p></span></div></div>
 <section className="collection section-shell" id="colecao"><div className="section-heading reveal"><div><span className="eyebrow">ENCONTRE A SUA FREQUÊNCIA.</span><h2>Seu som.<br/> <span>Seu ritmo.</span></h2></div><p>Para mergulhar. Para levar. Para compartilhar.<br/> Existe um VOLT para cada versão de você.</p></div><div className="collection-toolbar"><div className="category-tabs" aria-label="Categorias">{['Todos','Headphones','Earbuds','Speakers'].map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}{c==='Todos'&&<span>03</span>}</button>)}</div><label className="sort-control"><span className="sr-only">Ordenar produtos</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Em destaque</option><option value="low">Menor preço</option><option value="high">Maior preço</option></select><ChevronDown size={16}/></label></div><div className="product-grid">{filtered.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>
 <section className="experience section-shell" id="tecnologia"><div className="experience-copy reveal"><span className="eyebrow">O QUE VOCÊ NÃO OUVE IMPORTA.</span><h2>Menos mundo.<br/> <span>Mais música.</span></h2><p>O cancelamento ativo de ruído do V01 abre espaço para o que importa. Baixos que você sente. Detalhes que você descobre. Sua música, sem interrupções.</p><div className="experience-features"><div><AudioLines size={21}/><span>ANC adaptativo<small>O silêncio se ajusta a você.</small></span></div><div><Headphones size={21}/><span>Drivers de 40 mm<small>Precisão em cada frequência.</small></span></div><div><BatteryFull size={21}/><span>40 horas de autonomia<small>Do primeiro play ao último bis.</small></span></div></div><button className="button outline" onClick={()=>store.open({type:'product',product:products[0]})}>Veja cada detalhe<Plus size={18}/></button></div><div className="frequency-lab reveal"><div className="lab-top"><span>VOLT SOUND LAB / 01</span><AudioLines size={19}/></div><div className={`waveform ${playing?'playing':''}`} aria-hidden="true">{Array.from({length:49},(_,i)=><span key={i} style={{'--height':`${18+Math.abs(Math.sin(i*.6))*35+Math.abs(Math.cos(i*.27))*75}px`,'--delay':`${i*.065}s`} as React.CSSProperties}/>)}</div><div className="lab-title"><span>FEEL THE<br/> FREQUENCY.</span><small>130.81 — 261.63 Hz</small></div><button className={`sound-demo ${playing?'active':''}`} onClick={toggleSound} aria-pressed={playing}>{playing?<Pause size={18}/>:<Play size={18}/>}<span>{playing?'Pausar experiência':'Experimente a frequência'}</span></button><div className="lab-bottom"><span>ÁUDIO AMBIENTE · VOLUME SUAVE</span><span>ESTÉREO / 44.1</span></div></div></section>
 <section className="manifesto" id="manifesto"><div className="section-shell"><span className="eyebrow">FEITO PARA QUEM SENTE.</span><h2>Não é só som.<br/> É o seu <em>estado de espírito.</em></h2><div className="manifesto-bottom"><span className="manifesto-logo">VOLT®</span><p>O primeiro acorde. A estrada aberta. Seu lugar no mundo.<br/> Criamos áudio para os momentos que merecem ser sentidos.</p></div></div></section>
 <section className="portable section-shell"><div className="portable-visual reveal"><div className="portable-top"><span className="eyebrow">V02 AIR</span><span className="pill">POCKET-SIZED FREEDOM</span></div><img src={import.meta.env.BASE_URL+'images/earbuds.webp'} alt="Earbuds V02 Air no estojo de carregamento graphite" loading="lazy" width="720" height="720"/><span className="portable-word" aria-hidden="true">AIR.</span></div><div className="portable-copy reveal"><span className="eyebrow">A LIBERDADE É LEVE.</span><h2>Pequeno no tamanho.<br/> <span>Imenso no som.</span></h2><p>O V02 Air vai para onde você vai. No bolso, na rotina, na sua playlist favorita. Sem fios. Sem peso. Sem ficar para trás.</p><div className="portable-stats"><div><strong>32 h</strong><span>Com o estojo</span></div><div><strong>IPX4</strong><span>Pronto para o dia</span></div><div><strong>11 mm</strong><span>Drivers potentes</span></div></div><button className="button primary" onClick={()=>store.open({type:'product',product:products[1]})}>Conheça o V02<Plus size={18}/></button></div></section>
 <section className="service-strip section-shell"><div><Truck size={22}/><span><strong>O som chega até você.</strong><small>Frete grátis acima de R$ 500.</small></span></div><div><RotateCcw size={22}/><span><strong>Experimente no seu ritmo.</strong><small>30 dias para mudar de ideia.</small></span></div><div><ShieldCheck size={22}/><span><strong>Feito para durar.</strong><small>Design e construção de precisão.</small></span></div></section>
 <section className="faq section-shell"><div className="reveal"><span className="eyebrow">VAMOS SINTONIZAR.</span><h2>Boa pergunta.<br/> <span>Resposta clara.</span></h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div key={q} className="faq-item"><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={19}/>:<Plus size={19}/>}</button><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="last-call"><div className="section-shell"><span className="eyebrow">SEU MUNDO ESTÁ NO PLAY.</span><h2>AUMENTE<br/> AS POSSIBILIDADES.</h2><button className="button dark" onClick={()=>scrollTo('colecao')}>Encontre o seu VOLT<Plus size={18}/></button><span className="last-volume" aria-hidden="true"><AudioLines size={210} strokeWidth={.75}/></span></div></section>
 </main><footer className="site-footer section-shell"><div className="footer-top"><div><a className="wordmark" href="#inicio">VOLT<span>®</span></a><p>Your world.<br/> Your frequency.</p></div><div><span className="eyebrow">SINTONIZE</span><button onClick={()=>scrollTo('colecao')}>Todos os produtos</button><button onClick={()=>scrollTo('tecnologia')}>A experiência</button><button onClick={()=>store.open({type:'favorites'})}>Seus favoritos</button></div><div><span className="eyebrow">SUPORTE</span><button onClick={()=>info('Entrega e garantia','VOLT é uma marca fictícia de um projeto de portfólio. As especificações e condições são conceituais. Nenhum produto é vendido, cobrado ou enviado.')}>Entrega e garantia</button><button onClick={()=>info('Privacidade','A sacola e os favoritos ficam apenas neste navegador. Dados preenchidos no checkout não são enviados nem armazenados. Esta experiência não utiliza rastreadores ou publicidade.')}>Privacidade</button><button onClick={()=>info('Sobre este projeto','VOLT é uma experiência de e-commerce frontend criada por Artur Guerra. As fotografias são originais, as marcas e produtos são fictícios e os modelos 3D são conceituais.')}>Sobre o projeto</button></div><div className="footer-statement">STAY<br/> <span>AMPLIFIED.</span><AudioLines size={30}/></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} VOLT® · Design por Artur Guerra</span><span>Projeto de portfólio · compra demonstrativa</span><span>BR / PT</span></div></footer></>;
}
