import { useEffect, useRef, useState } from 'react';
import type { PointerEvent } from 'react';
import { Box, ChevronDown, Heart, Menu, Search, ShoppingBag, X, Truck, RotateCcw, Sparkles, Plus, Minus, MoveUpRight } from 'lucide-react';
import { products } from './products';
import { money } from './types';
import { ProductCard, StoreProvider, useStore } from './Commerce';
const scrollTo=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
export default function App(){return <StoreProvider brand="FORMA" products={products}><Forma/></StoreProvider>;}
function Forma(){
 const store=useStore();const [category,setCategory]=useState('Todos');const [sort,setSort]=useState('featured');const [menu,setMenu]=useState(false);const [faq,setFaq]=useState<number|null>(0);const hero=useRef<HTMLDivElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[category,sort]);
 const tilt=(e:PointerEvent<HTMLDivElement>)=>{if(e.pointerType!=='mouse'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rect=e.currentTarget.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width-.5;const y=(e.clientY-rect.top)/rect.height-.5;hero.current?.style.setProperty('--rx',`${-y*7}deg`);hero.current?.style.setProperty('--ry',`${x*9}deg`);};
 const navigate=(id:string)=>{setMenu(false);scrollTo(id);};
 const filtered=products.filter(p=>category==='Todos'||p.category===category).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:products.indexOf(a)-products.indexOf(b));
 const info=(title:string,body:string)=>store.open({type:'info',title,body});
 const faqs=[['Como funciona a entrega?','Na experiência demonstrativa, pedidos acima de R$ 500 recebem frete grátis. Os produtos, prazos e condições são fictícios; nenhum pedido é enviado.'],['Posso ver a peça de todos os ângulos?','Sim. Abra um produto e toque em “Explorar em 3D”. Você pode girar, aproximar e experimentar os acabamentos em um modelo conceitual da peça.'],['E se eu mudar de ideia?','A coleção foi pensada para você explorar com calma. Na simulação, apresentamos troca em 30 dias. Este projeto é um portfólio e não realiza vendas.']];
 return <><a className="skip-link" href="#colecao">Ir para a coleção</a><div className="announcement"><span>Design para viver. Frete grátis acima de R$ 500.</span><span>Feito para ficar.</span></div><header className="site-header"><a className="wordmark" href="#inicio" aria-label="FORMA, início">forma<span>®</span></a><nav aria-label="Navegação principal"><a href="#colecao" onClick={e=>{e.preventDefault();navigate('colecao');}}>Coleção <span>03</span></a><a href="#sobre" onClick={e=>{e.preventDefault();navigate('sobre');}}>Nossa forma</a><a href="#destaque" onClick={e=>{e.preventDefault();navigate('destaque');}}>Objeto do mês</a></nav><div className="header-actions"><button className="icon-button" aria-label="Buscar produtos" onClick={()=>store.open({type:'search'})}><Search size={20}/></button><button className="icon-button favorites-button" aria-label="Ver favoritos" onClick={()=>store.open({type:'favorites'})}><Heart size={20}/>{store.favorites.length>0&&<span className="count">{store.favorites.length}</span>}</button><button className="bag-button" aria-label={`Abrir sacola, ${store.count} itens`} onClick={()=>store.open({type:'cart'})}><ShoppingBag size={19}/><span>Sacola</span><span className="bag-count">{store.count}</span></button><button className="mobile-menu icon-button" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<nav className="mobile-navigation" aria-label="Navegação móvel"><button onClick={()=>navigate('colecao')}>Coleção</button><button onClick={()=>navigate('sobre')}>Nossa forma</button><button onClick={()=>navigate('destaque')}>Objeto do mês</button><button onClick={()=>{setMenu(false);store.open({type:'favorites'});}}>Favoritos</button></nav>}
 <main id="inicio"><section className="hero section-shell"><div className="hero-copy"><div className="eyebrow"><span className="small-spark">✳</span> DESIGN QUE SE SENTE.</div><h1>A casa tem<br/> a sua <em>forma.</em></h1><p>Peças com presença. Texturas que acolhem.<br className="desktop-break"/>Uma coleção para transformar espaços em lugares.</p><div className="hero-buttons"><button className="button primary" onClick={()=>scrollTo('colecao')}>Encontre a sua peça<Plus size={18}/></button><button className="hero-3d" onClick={()=>store.open({type:'product',product:products[0]})}><Box size={18}/>Explore em 3D</button></div><div className="hero-footnote"><span className="edition-label">COLEÇÃO<br/> PERMANENTE / 26</span><span>Design autoral.<br/> Para a sua vida real.</span><span className="hero-mini-mark">f.</span></div></div><div className="hero-art" ref={hero} onPointerMove={tilt} onPointerLeave={()=>{hero.current?.style.setProperty('--rx','0deg');hero.current?.style.setProperty('--ry','0deg');}}><div className="hero-art-top"><span>01 / FAVORITA DA CASA</span><span className="round-icon"><Sparkles size={19}/></span></div><span className="hero-outline-word" aria-hidden="true">nuvem.</span><div className="hero-halo"/><button className="hero-product" onClick={()=>store.open({type:'product',product:products[0]})} aria-label="Conhecer a Poltrona Nuvem"><img src={import.meta.env.BASE_URL+'images/chair.webp'} alt="Poltrona Nuvem em bouclé verde musgo com pés de aço inox" width="1000" height="1000" fetchPriority="high"/><span className="floating-tag"><Plus size={20}/></span></button><div className="hero-art-bottom"><div><span>POLTRONA NUVEM</span><p>Seu novo lugar favorito.</p></div><button onClick={()=>store.open({type:'product',product:products[0]})}>{money(products[0].price)}<MoveUpRight size={18}/></button></div></div></section>
 <div className="service-strip section-shell"><span><Truck size={21}/><strong>Frete grátis</strong> acima de R$ 500</span><span><RotateCcw size={21}/><strong>30 dias</strong> para mudar de ideia</span><span><Box size={21}/><strong>Design autoral</strong> em cada detalhe</span></div>
 <section className="collection section-shell" id="colecao"><div className="section-heading reveal"><div><span className="eyebrow">UMA COLEÇÃO. MUITAS POSSIBILIDADES.</span><h2>Escolhas com<br/> <em>personalidade.</em></h2></div><p>O essencial pode ser extraordinário.<br/> Encontre o detalhe que faz a sua casa ser sua.</p></div><div className="collection-toolbar"><div className="category-tabs" aria-label="Categorias">{['Todos','Assentos','Iluminação','Objetos'].map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}{c==='Todos'&&<span>03</span>}</button>)}</div><label className="sort-control"><span className="sr-only">Ordenar produtos</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Em destaque</option><option value="low">Menor preço</option><option value="high">Maior preço</option></select><ChevronDown size={16}/></label></div><div className="product-grid">{filtered.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div><div className="collection-note"><span>01 — 03</span><p>Três peças. Infinitas formas de morar.</p><span>CURADORIA FORMA®</span></div></section>
 <section className="manifesto" id="sobre"><div className="manifesto-inner section-shell"><div className="manifesto-intro reveal"><span className="eyebrow">NOSSA FORMA DE VER O MUNDO</span><h2>Menos coisas.<br/> Mais <em>significado.</em></h2><p>Uma casa não precisa ser perfeita.<br/> Precisa ser sua.</p></div><div className="manifesto-values"><div className="reveal"><span>01</span><h3>Design que fica.</h3><p>Formas que atravessam tendências e continuam fazendo sentido, ano após ano.</p></div><div className="reveal"><span>02</span><h3>Matéria que conversa.</h3><p>Madeira, tecido e metal. Texturas escolhidas para serem vistas e, principalmente, sentidas.</p></div><div className="reveal"><span>03</span><h3>Espaço para ser.</h3><p>Peças que se encontram com a sua história. Você escolhe a forma de viver.</p></div></div></div><div className="manifesto-word" aria-hidden="true">feito para ficar.</div></section>
 <section className="spotlight section-shell" id="destaque"><div className="spotlight-art reveal"><span className="eyebrow">UM NOVO PONTO DE LUZ.</span><img src={import.meta.env.BASE_URL+'images/lamp.webp'} alt="Luminária Dome em metal esmaltado vinho" loading="lazy" width="720" height="720"/><div className="spotlight-label">DOME<span>OBJETO Nº 02</span></div></div><div className="spotlight-copy reveal"><span className="eyebrow">O DETALHE MUDA TUDO.</span><h2>Pequena na forma.<br/> Grande na<br/> <em>atmosfera.</em></h2><p>A Dome tem curvas suaves, cor marcante e aquela luz que convida a ficar um pouco mais. Um objeto, outro jeito de sentir a casa.</p><div className="spotlight-specs"><div><span>2700K</span><small>Luz quente</small></div><div><span>38 cm</span><small>De presença</small></div><div><span>3 cores</span><small>De personalidade</small></div></div><button className="button primary" onClick={()=>store.open({type:'product',product:products[1]})}>Conhecer a Dome<Plus size={18}/></button></div></section>
 <section className="faq section-shell"><div className="reveal"><span className="eyebrow">PODE CHEGAR MAIS PERTO.</span><h2>Sem dúvidas.<br/> <em>Com calma.</em></h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div key={q} className={`faq-item ${faq===i?'open':''}`}><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={20}/>:<Plus size={20}/>}</button><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
 <section className="last-call"><div className="section-shell"><span className="eyebrow">O PRÓXIMO CAPÍTULO É SEU.</span><h2>Dê a sua forma.</h2><button className="button dark" onClick={()=>scrollTo('colecao')}>Explorar a coleção<Plus size={18}/></button><span className="last-spark" aria-hidden="true">✳</span></div></section>
 </main><footer className="site-footer section-shell"><div className="footer-top"><a href="#inicio" className="wordmark">forma<span>®</span></a><p>Design que se sente.<br/> Feito para ficar.</p><div><span className="eyebrow">EXPLORE</span><button onClick={()=>scrollTo('colecao')}>Coleção permanente</button><button onClick={()=>scrollTo('sobre')}>Nossa forma</button><button onClick={()=>store.open({type:'favorites'})}>Seus favoritos</button></div><div><span className="eyebrow">PODE CONTAR COM A GENTE</span><button onClick={()=>info('Entrega e trocas','Esta loja é uma experiência demonstrativa. As condições de frete grátis acima de R$ 500 e troca em 30 dias fazem parte da apresentação. Nenhum produto é vendido ou enviado.')}>Entrega e trocas</button><button onClick={()=>info('Privacidade','Seus favoritos e sua sacola ficam apenas neste navegador. Nenhum dado do checkout é enviado, armazenado ou compartilhado. Não utilizamos rastreadores ou cookies de publicidade.')}>Privacidade</button><button onClick={()=>info('Sobre este projeto','FORMA é uma marca fictícia criada para um projeto de portfólio de Artur Guerra. Catálogo, fotografias e modelos 3D apresentam uma experiência de e-commerce exclusivamente frontend.')}>Sobre o projeto</button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} FORMA® · Design por Artur Guerra</span><span>Projeto de portfólio · compra demonstrativa</span><span>FEITO NO BRASIL.</span></div></footer></>;
}
